---
- hosts: localhost
  become: no
  vars:
    - src_dir: src
    - work_dir: work
    - user_name: "{{ansible_facts['env']['USER']}}"

  tasks:
    - name: install apache2
      apt:
        name: apache2
      become: yes
    - name: install apache2-dev
      apt:
        name: apache2-dev
      become: yes
    - name: start apache2 and enabled
      service: name=apache2 state=started enabled=yes
      become: yes
    - name: change owner
      file: dest=/var/www/html owner="{{user_name}}" recurse=yes
      become: yes
    - name: change group
      file: dest=/var/www/html group="{{user_name}}" recurse=yes
      become: yes

  handlers:
