---
- hosts: localhost
  become: yes
  vars:
    - src_dir: src
    - work_dir: work

  tasks:
    - name: install php
      apt:
        name: php
    - name: install php-mbstring
      apt:
        name: php-mbstring
    - name: install php-gd
      apt:
        name: php-gd
    - name: install php-intl
      apt:
        name: php-intl
    - name: install php-xml
      apt:
        name: php-xml
    - name: install php-mysql
      apt:
        name: php-mysql
    - name: install php-ldap
      apt:
        name: php-ldap
    - name: install php-gmp
      apt:
        name: php-gmp
    - name: install php-curl
      apt:
        name: php-curl
    - name: install php-xmlrpc
      apt:
        name: php-xmlrpc
    - name: install php-soap
      apt:
        name: php-soap
    - name: install php-zip
      apt:
        name: php-zip
    - name: install php-sqlite3
      apt:
        name: php-sqlite3
    - name: install php-xdebug
      apt:
        name: php-xdebug
    - name: copy xdebug.ini 
      copy: src=xdebug.ini dest=/etc/php/8.1/mods-available/xdebug.ini backup=yes

  handlers:
