---
- hosts: localhost
  become: yes
  vars:
#    - anaconda_version: anaconda3-2019.10
    # - anaconda_version: anaconda3-2020.11
    - anaconda_version: anaconda3-2022.05
    - src_dir: src
    - work_dir: work

  tasks:

    - name: curl https://pyenv.run | bash
      shell: curl https://pyenv.run | bash
      become: no

    - name: edit .bashrc (1)
      shell: /usr/bin/echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
      become: no
    - name: edit .bashrc (2)
      shell: /usr/bin/echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
      become: no
    - name: edit .bashrc (3)
      shell: /usr/bin/echo 'eval "$(pyenv init -)"' >> ~/.bashrc
      become: no

    - name: Install Anaconda
      shell: /home/vagrant/.pyenv/bin/pyenv install {{anaconda_version}}
      become: no
    - name: Rehash
      shell: /home/vagrant/.pyenv/bin/pyenv rehash
      become: no

    - name: Set Global
      shell: /home/vagrant/.pyenv/bin/pyenv global {{anaconda_version}}
      become: no
    - name: edit .bashrc
      shell: /usr/bin/echo 'export PATH="$PYENV_ROOT/versions/{{anaconda_version}}/bin/:$PATH"' >> ~/.bashrc
      become: no
    - name: Source
      shell: source ~/.bashrc
      become: no

    - name: Update Conda
      shell: /home/vagrant/.pyenv/versions/{{anaconda_version}}/bin/conda update conda -y
      become: no

  handlers:
