---
- hosts: localhost
  become: no
  vars:
    # - anaconda_version: anaconda3-2019.10
    # - anaconda_version: anaconda3-2020.11
    - anaconda_version: anaconda3-2022.05
    - src_dir: src
    - work_dir: work
    - pyenv_install: "{{ansible_facts['env']['HOME']}}/.pyenv/bin/pyenv install {{anaconda_version}}"
    - pyenv_rehash: "{{ansible_facts['env']['HOME']}}/.pyenv/bin/pyenv rehash"
    - pyenv_global: "{{ansible_facts['env']['HOME']}}/.pyenv/bin/pyenv global {{anaconda_version}}"
    - conda_update: "{{ansible_facts['env']['HOME']}}/.pyenv/versions/{{anaconda_version}}/bin/conda update conda -y"

  tasks:

    - name: curl https://pyenv.run | bash
      shell: curl https://pyenv.run | bash
      become: no

    - name: edit .bashrc (1)
      shell: /usr/bin/echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
      become: no
    - name: edit .bashrc (2)
      shell: /usr/bin/echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
      become: no
    - name: edit .bashrc (3)
      shell: /usr/bin/echo 'eval "$(pyenv init -)"' >> ~/.bashrc
      become: no

    - name: Install Anaconda
      shell: "{{pyenv_install}}"
      become: no
    - name: Rehash
      shell: "{{pyenv_rehash}}"
      become: no

    - name: Set Global
      shell: "{{pyenv_global}}"
      become: no
    - name: edit .bashrc
      shell: /usr/bin/echo 'export PATH="$PYENV_ROOT/versions/{{anaconda_version}}/bin:$PATH"' >> ~/.bashrc
      become: no
    - name: Source
      shell: /usr/bin/sh ~/.bashrc
      become: no

    - name: Update Conda
      shell: "{{conda_update}}"
      become: no

  handlers:
